#!/usr/bin/env python3

from __future__ import annotations

import argparse
import math
import subprocess
import sys
from pathlib import Path

import pandas as pd
import pyBigWig


def _find_project_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "repo_paths.py").exists():
            return candidate
    raise FileNotFoundError(
        f"Could not find repo_paths.py while walking upward from {start}"
    )


SCRIPT_PATH = Path(__file__).resolve()
PROJECT_ROOT = _find_project_root(SCRIPT_PATH.parent)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from repo_paths import REFERENCE_DATA_DIR  # noqa: E402


HELPER_FILES_DIR = (
    PROJECT_ROOT
    / "analysis"
    / "01_region_calling_analysis"
    / "utils"
    / "helper_files"
)
MICROARRAY_PREP_R = HELPER_FILES_DIR / "microarray_data_prep.r"
CHAIN_FILE = REFERENCE_DATA_DIR / "hg19ToHg38.over.chain"
BED_COLUMNS = ["chrom", "start", "end", "probe"]
OUTPUT_COLUMNS = ["chrom", "start", "end", "beta", "probe"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Downsample a WGBS bigWig to HM450K probe loci using the same probe BED "
            "generation step as methyl_tool_comparator.py, then write a sparse "
            "450k-style bigWig for IGV."
        )
    )
    parser.add_argument(
        "--input-bw",
        required=True,
        type=Path,
        help="Input WGBS bigWig (.bw or .bigWig) containing methylation beta values.",
    )
    parser.add_argument(
        "--genome",
        required=True,
        choices=["hg19", "hg38"],
        help="Genome build used to generate the HM450K probe BED.",
    )
    parser.add_argument(
        "--output-bw",
        required=True,
        type=Path,
        help="Output sparse HM450K bigWig path.",
    )
    parser.add_argument(
        "--output-tsv",
        type=Path,
        default=None,
        help=(
            "Optional TSV to write sampled probe methylation values. "
            "Defaults to <output-bw stem>.tsv."
        ),
    )
    parser.add_argument(
        "--probe-bed",
        type=Path,
        default=None,
        help=(
            "Optional cache path for the raw HM450K BED generated by the repo's "
            "microarray_data_prep.r helper."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing outputs and regenerate the cached probe BED.",
    )
    return parser.parse_args()


def default_output_tsv(output_bw: Path) -> Path:
    if output_bw.suffix:
        return output_bw.with_suffix(".tsv")
    return output_bw.with_name(f"{output_bw.name}.tsv")


def default_probe_bed(output_bw: Path, genome: str) -> Path:
    return output_bw.parent / f"HM450K_{genome}_locations.bed"


def ensure_parent_dir(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def ensure_hm450k_bed(genome: str, probe_bed: Path, force: bool) -> Path:
    if probe_bed.exists() and not force:
        return probe_bed

    if not MICROARRAY_PREP_R.exists():
        raise FileNotFoundError(f"Missing helper script: {MICROARRAY_PREP_R}")
    if genome == "hg38" and not CHAIN_FILE.exists():
        raise FileNotFoundError(f"Missing liftOver chain file: {CHAIN_FILE}")

    ensure_parent_dir(probe_bed)
    cmd = [
        "Rscript",
        str(MICROARRAY_PREP_R),
        "--genome",
        genome,
        "--out-bed",
        str(probe_bed),
    ]
    if genome == "hg38":
        cmd.extend(["--chain-file", str(CHAIN_FILE)])

    subprocess.run(cmd, check=True)
    return probe_bed


def canonical_chrom_name(chrom: str) -> str | None:
    chrom = str(chrom)
    if chrom.startswith("chr"):
        core = chrom[3:]
    else:
        core = chrom
    if core in {str(i) for i in range(1, 23)} | {"X", "Y"}:
        return f"chr{core}"
    return None


def build_probe_to_input_chrom_map(
    input_chrom_sizes: dict[str, int],
) -> dict[str, str]:
    canonical_to_input: dict[str, str] = {}
    for chrom in input_chrom_sizes:
        canonical = canonical_chrom_name(chrom)
        if canonical is not None and canonical not in canonical_to_input:
            canonical_to_input[canonical] = chrom
    return canonical_to_input


def load_probe_bed(probe_bed: Path, chrom_map: dict[str, str]) -> pd.DataFrame:
    probe_df = pd.read_csv(
        probe_bed,
        sep="\t",
        header=None,
        names=BED_COLUMNS,
        usecols=[0, 1, 2, 3],
    )
    probe_df = probe_df.loc[probe_df["chrom"].isin(chrom_map)].copy()
    if probe_df.empty:
        raise RuntimeError(
            "The generated HM450K BED does not share canonical chromosome names "
            "with the input bigWig. Check genome build and chromosome naming."
        )

    probe_df["chrom"] = probe_df["chrom"].map(chrom_map)
    probe_df["start"] = pd.to_numeric(probe_df["start"], errors="raise").astype(int)
    probe_df["end"] = pd.to_numeric(probe_df["end"], errors="raise").astype(int)
    probe_df["probe"] = probe_df["probe"].astype(str)
    return probe_df.reset_index(drop=True)


def sort_by_input_chrom_order(
    df: pd.DataFrame,
    input_chrom_sizes: dict[str, int],
) -> pd.DataFrame:
    chrom_order = list(input_chrom_sizes.keys())
    ordered_df = df.loc[df["chrom"].isin(chrom_order)].copy()
    ordered_df["chrom"] = pd.Categorical(
        ordered_df["chrom"],
        categories=chrom_order,
        ordered=True,
    )
    ordered_df = ordered_df.sort_values(["chrom", "start", "end"]).reset_index(
        drop=True
    )
    ordered_df["chrom"] = ordered_df["chrom"].astype(str)
    return ordered_df


def sample_bigwig_at_probes(
    input_bw: Path,
    probe_df: pd.DataFrame,
) -> tuple[pd.DataFrame, dict[str, int]]:
    with pyBigWig.open(str(input_bw)) as bw_handle:
        input_chrom_sizes = bw_handle.chroms()
        sampled_rows: list[tuple[str, int, int, float, str]] = []
        ordered_probe_df = sort_by_input_chrom_order(probe_df, input_chrom_sizes)

        for chrom, chrom_df in ordered_probe_df.groupby("chrom", sort=False):
            chrom_size = int(input_chrom_sizes[chrom])
            print(
                f"Sampling {len(chrom_df):,} HM450K probes from {chrom}...",
                file=sys.stderr,
            )
            for row in chrom_df.itertuples(index=False):
                start = int(row.start)
                end = int(row.end)
                if start < 0 or end <= start or end > chrom_size:
                    continue
                value = bw_handle.stats(chrom, start, end, type="mean", exact=True)[0]
                if value is None or not math.isfinite(value):
                    continue
                sampled_rows.append((chrom, start, end, float(value), str(row.probe)))

    sampled_df = pd.DataFrame(sampled_rows, columns=OUTPUT_COLUMNS)
    if sampled_df.empty:
        raise RuntimeError(
            "No finite methylation values were sampled at HM450K loci. "
            "Check that the input bigWig matches the requested genome build."
        )
    return sampled_df, input_chrom_sizes


def write_bigwig(
    sampled_df: pd.DataFrame,
    input_chrom_sizes: dict[str, int],
    output_bw: Path,
) -> Path:
    ensure_parent_dir(output_bw)
    grouped_df = (
        sampled_df.groupby(["chrom", "start", "end"], as_index=False)
        .agg(beta=("beta", "mean"), probe_count=("probe", "size"))
    )
    duplicate_probe_rows = int(grouped_df["probe_count"].sum() - len(grouped_df))
    duplicate_loci = int(grouped_df["probe_count"].gt(1).sum())
    if duplicate_probe_rows:
        print(
            "Collapsing "
            f"{duplicate_probe_rows:,} duplicate probe rows across "
            f"{duplicate_loci:,} shared genomic loci before writing bigWig.",
            file=sys.stderr,
        )

    ordered_df = sort_by_input_chrom_order(
        grouped_df[["chrom", "start", "end", "beta"]],
        input_chrom_sizes,
    )
    overlap_mask = ordered_df.groupby("chrom")["end"].shift(fill_value=-1) > ordered_df["start"]
    if overlap_mask.any():
        overlap_df = ordered_df.loc[overlap_mask, ["chrom", "start", "end"]].head(5)
        raise RuntimeError(
            "Some sampled intervals still overlap after collapsing duplicate loci, "
            "so they cannot be written to bigWig. First overlaps:\n"
            f"{overlap_df.to_string(index=False)}"
        )

    chrom_header = [(chrom, int(size)) for chrom, size in input_chrom_sizes.items()]

    with pyBigWig.open(str(output_bw), "w") as bw_handle:
        bw_handle.addHeader(chrom_header)
        bw_handle.addEntries(
            ordered_df["chrom"].tolist(),
            ordered_df["start"].astype(int).tolist(),
            ends=ordered_df["end"].astype(int).tolist(),
            values=ordered_df["beta"].astype(float).tolist(),
        )
    return output_bw


def write_tsv(sampled_df: pd.DataFrame, output_tsv: Path) -> Path:
    ensure_parent_dir(output_tsv)
    sampled_df.to_csv(output_tsv, sep="\t", index=False)
    return output_tsv


def validate_args(args: argparse.Namespace) -> None:
    if not args.input_bw.exists():
        raise FileNotFoundError(f"Input bigWig not found: {args.input_bw}")

    output_tsv = args.output_tsv or default_output_tsv(args.output_bw)
    for path in [args.output_bw, output_tsv]:
        if path.exists() and not args.force:
            raise FileExistsError(
                f"Refusing to overwrite existing output without --force: {path}"
            )


def main() -> int:
    args = parse_args()
    validate_args(args)

    output_tsv = args.output_tsv or default_output_tsv(args.output_bw)
    probe_bed = args.probe_bed or default_probe_bed(args.output_bw, args.genome)

    ensure_hm450k_bed(args.genome, probe_bed, force=args.force)

    with pyBigWig.open(str(args.input_bw)) as bw_handle:
        input_chrom_sizes = bw_handle.chroms()
    chrom_map = build_probe_to_input_chrom_map(input_chrom_sizes)
    if not chrom_map:
        raise RuntimeError(
            "Input bigWig does not expose canonical autosome/X/Y chromosome names."
        )

    probe_df = load_probe_bed(probe_bed, chrom_map)
    sampled_df, input_chrom_sizes = sample_bigwig_at_probes(args.input_bw, probe_df)
    sampled_df = sort_by_input_chrom_order(sampled_df, input_chrom_sizes)

    write_tsv(sampled_df, output_tsv)
    write_bigwig(sampled_df, input_chrom_sizes, args.output_bw)

    print(f"Wrote sampled probe table: {output_tsv}")
    print(f"Wrote sparse HM450K bigWig: {args.output_bw}")
    print(f"Used raw HM450K BED cache: {probe_bed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
