genome: hg38
meth_file: /uufs/chpc.utah.edu/common/home/u0914269/clement/projects/20260624_methylseg/data/methylation_data/GSM5652251_Pancreas-Beta-Z00000455.hg38.beta
sample: GSM5652251_Pancreas-Beta-Z00000455.hg38
