genome: hg19
meth_file: /uufs/chpc.utah.edu/common/home/u0914269/clement/projects/20260624_methylseg/data/methylation_data/GSM5652250_Pancreas-Beta-Z00000452.beta
sample: GSM5652250_Pancreas-Beta-Z00000452
