genome: hg38
meth_file: /uufs/chpc.utah.edu/common/home/u0914269/clement/projects/20260624_methylseg/data/methylation_data/WGBS_colon-primary-normal_3_meth.bed.gz
sample: WGBS_colon-primary-normal_3_meth
